#!/bin/bash

DEF_FILE="project.def"
OUT_FILE="objs.mk"

# Associative arrays to store configuration
declare -A DIR_GLOBS
declare -A DIR_EXCLUDES
declare -a DIR_ORDER
declare -A DIR_PATHS
declare -A DIR_EXTRA_FLAGS

declare -a TARGETS_TYPE
declare -a TARGETS_NAME
declare -A TARGETS_DIRS
declare -A TARGETS_FLAGS
declare -A TARGETS_LIBS
declare -A TARGETS_DEPS
declare -A TARGET_TYPE_MAP

# Helper to sanitize strings for Make variable names (replace /, ., - with _)
sanitize_var() {
    echo "$1" | tr '/.-' '___'
}

# --- 1. Parse project.def ---

CURRENT_DIR=""
CURRENT_TARGET=""
CONTEXT_TYPE=""

while read -r line; do
    # Skip comments and empty lines
    [[ "$line" =~ ^#.*$ ]] && continue
    [[ -z "$line" ]] && continue

    # Read tokens
    read -r cmd arg1 arg2 <<< "$line"

    case "$cmd" in
        dir)
            # Usage: dir <name> <path> <glob>
            # Example: dir core src/foo *.c
            # Also supports: dir NAME=PATH GLOB
            if [[ "$arg1" == *"="* ]]; then
                CURRENT_DIR="${arg1%%=*}"
                PATH_VAL="${arg1##*=}"
                GLOB_VAL="$arg2"
            else
                CURRENT_DIR="$arg1"
                read -r PATH_VAL GLOB_VAL <<< "$arg2"
            fi
            DIR_PATHS["$CURRENT_DIR"]="$PATH_VAL"
            DIR_GLOBS["$CURRENT_DIR"]="$GLOB_VAL"
            DIR_ORDER+=("$CURRENT_DIR")
            CONTEXT_TYPE="dir"
            ;;
        exclude)
            # Usage: exclude <glob>
            # Applies to the most recently defined directory
            if [[ -n "$CURRENT_DIR" ]]; then
                EXISTING="${DIR_EXCLUDES[$CURRENT_DIR]}"
                if [[ -n "$EXISTING" ]]; then
                    DIR_EXCLUDES["$CURRENT_DIR"]="$EXISTING $arg1 $arg2"
                else
                    DIR_EXCLUDES["$CURRENT_DIR"]="$arg1 $arg2"
                fi
            fi
            ;;
        add)
            if [[ -n "$CURRENT_DIR" ]]; then
                EXISTING="${DIR_GLOBS[$CURRENT_DIR]}"
                if [[ -n "$EXISTING" ]]; then
                    DIR_GLOBS["$CURRENT_DIR"]="$EXISTING $arg1 $arg2"
                else
                    DIR_GLOBS["$CURRENT_DIR"]="$arg1 $arg2"
                fi
            fi
            ;;
        flags)
            if [[ "$CONTEXT_TYPE" == "target" && -n "$CURRENT_TARGET" ]]; then
                EXISTING="${TARGETS_FLAGS[$CURRENT_TARGET]}"
                if [[ -n "$EXISTING" ]]; then
                    TARGETS_FLAGS["$CURRENT_TARGET"]="$EXISTING $arg1 $arg2"
                else
                    TARGETS_FLAGS["$CURRENT_TARGET"]="$arg1 $arg2"
                fi
            elif [[ -n "$CURRENT_DIR" ]]; then
                EXISTING="${DIR_EXTRA_FLAGS[$CURRENT_DIR]}"
                if [[ -n "$EXISTING" ]]; then
                    DIR_EXTRA_FLAGS["$CURRENT_DIR"]="$EXISTING $arg1 $arg2"
                else
                    DIR_EXTRA_FLAGS["$CURRENT_DIR"]="$arg1 $arg2"
                fi
            fi
            ;;
        libs)
            if [[ "$CONTEXT_TYPE" == "target" && -n "$CURRENT_TARGET" ]]; then
                EXISTING="${TARGETS_LIBS[$CURRENT_TARGET]}"
                if [[ -n "$EXISTING" ]]; then
                    TARGETS_LIBS["$CURRENT_TARGET"]="$EXISTING $arg1 $arg2"
                else
                    TARGETS_LIBS["$CURRENT_TARGET"]="$arg1 $arg2"
                fi
            fi
            ;;
        dep)
            if [[ -n "$CURRENT_TARGET" && -n "$arg1" ]]; then
                # arg2 captures all remaining arguments (e.g. "dep libA libB")
                NEW_DEPS="$arg1"
                [[ -n "$arg2" ]] && NEW_DEPS="$NEW_DEPS $arg2"

                EXISTING="${TARGETS_DEPS[$CURRENT_TARGET]}"
                if [[ -n "$EXISTING" ]]; then
                    TARGETS_DEPS["$CURRENT_TARGET"]="$EXISTING $NEW_DEPS"
                else
                    TARGETS_DEPS["$CURRENT_TARGET"]="$NEW_DEPS"
                fi
            fi
            ;;
        exe|lib|dll)
            # Usage: exe <name> <dir1> <dir2> ...
            # We need to capture all remaining arguments as directories
            DIRS="$arg2"
            
            TARGETS_TYPE+=("$cmd")
            TARGETS_NAME+=("$arg1")
            TARGETS_DIRS["$arg1"]="$DIRS"
            CURRENT_TARGET="$arg1"
            TARGET_TYPE_MAP["$arg1"]="$cmd"
            CONTEXT_TYPE="target"
            ;;
    esac
done < "$DEF_FILE"

# --- 2. Generate objs.mk ---

echo "# Generated by gen.sh on $(date)" > "$OUT_FILE"
echo "" >> "$OUT_FILE"

ALL_TARGETS=""

# Process Directories
for d in "${DIR_ORDER[@]}"; do
    PATH_VAL="${DIR_PATHS[$d]}"
    GLOB="${DIR_GLOBS[$d]}"
    EXCLUDES="${DIR_EXCLUDES[$d]}"
    EXTRA_FLAGS="${DIR_EXTRA_FLAGS[$d]}"
    SANITIZED_DIR=$(sanitize_var "$d")
    
    echo "# --- Directory: $d ($PATH_VAL) ---" >> "$OUT_FILE"
    
    #if [[ -n "$EXCLUDES" ]]; then
    #    echo "DEBUG: Directory $d exclusions: $EXCLUDES"
    #fi
    
    # Find source files
    # We use find with maxdepth 1 to simulate globbing in that specific dir
    # Then we filter exclusions
    
    # Construct find command
    # Note: We assume the script runs in the project root
    FIND_ARGS=()
    if [[ -n "$GLOB" ]]; then
        FIND_ARGS+=("(")
        FIRST=1
        set -f
        for g in $GLOB; do
            [[ $FIRST -eq 0 ]] && FIND_ARGS+=("-o")
            FIND_ARGS+=("-name" "$g")
            FIRST=0
        done
        set +f
        FIND_ARGS+=(")")
    fi
    #echo "DEBUG: Executing: find \"$PATH_VAL\" -maxdepth 1 ${FIND_ARGS[*]} -type f"
    FILES=$(find "$PATH_VAL" -maxdepth 1 "${FIND_ARGS[@]}" -type f | sort)
    
    OBJ_LIST=""
    
    for f in $FILES; do
        BASENAME=$(basename "$f")
        
        # Check exclusions
        SKIP=0
        for exc in $EXCLUDES; do
            # Use bash pattern matching
            if [[ "$BASENAME" == $exc ]]; then
                #echo "DEBUG:   Skipping $BASENAME (matches $exc)"
                SKIP=1
                break
            fi
        done
        
        if [[ $SKIP -eq 1 ]]; then
            continue
        fi
        
        # Determine Object Path (use logical name)
        OBJ="objs/${d}/${BASENAME%.*}.o"
        DIR_PATH=$(dirname "$OBJ")
        
        # Add to list
        OBJ_LIST="$OBJ_LIST $OBJ"
        
        # Determine Compiler based on extension
        EXT="${f##*.}"
        COMPILER="\$(CC)"
        FLAGS="\$(CFLAGS)"
        
        if [[ "$EXT" == "cpp" || "$EXT" == "cc" || "$EXT" == "C" ]]; then
            COMPILER="\$(CXX)"
            FLAGS="\$(CXXFLAGS)"
        fi
        
        # Write Build Rule
        # We use explicit rules to allow per-directory flags
        echo "$OBJ: $f" >> "$OUT_FILE"
        echo -e "\t@mkdir -p $DIR_PATH" >> "$OUT_FILE"
        echo -e "\t$COMPILER $FLAGS \$(CPPFLAGS) -I$PATH_VAL $EXTRA_FLAGS \$(DIR_${SANITIZED_DIR}_CPPFLAGS) \$(DIR_${SANITIZED_DIR}_CFLAGS) -c $f -o $OBJ" >> "$OUT_FILE"
        echo "" >> "$OUT_FILE"
    done
    
    # Define variable for this directory's objects
    echo -n "DIR_${SANITIZED_DIR}_OBJS =" >> "$OUT_FILE"
    for obj in $OBJ_LIST; do
        echo " \\" >> "$OUT_FILE"
        echo -n "    $obj" >> "$OUT_FILE"
    done
    echo "" >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
done

# Process Targets
COUNT=${#TARGETS_TYPE[@]}
for ((i=0; i<COUNT; i++)); do
    TYPE="${TARGETS_TYPE[$i]}"
    NAME="${TARGETS_NAME[$i]}"
    DIRS="${TARGETS_DIRS[$NAME]}"
    
    # Auto-include directory if it matches target name
    if [[ -n "${DIR_PATHS[$NAME]}" ]]; then
        FOUND=0
        for d in $DIRS; do
            if [[ "$d" == "$NAME" ]]; then
                FOUND=1
                break
            fi
        done
        [[ $FOUND -eq 0 ]] && DIRS="$DIRS $NAME"
    fi
    
    SANITIZED_TARGET=$(sanitize_var "$NAME")
    
    TARGET_OBJS_VAR="TGT_${SANITIZED_TARGET}_OBJS"
    T_FLAGS="${TARGETS_FLAGS[$NAME]}"
    T_LIBS="${TARGETS_LIBS[$NAME]}"
    
    # Aggregate objects from included directories
    echo -n "${TARGET_OBJS_VAR} =" >> "$OUT_FILE"
    for d in $DIRS; do
        SANITIZED_DIR=$(sanitize_var "$d")
        echo " \\" >> "$OUT_FILE"
        echo -n "    \$(DIR_${SANITIZED_DIR}_OBJS)" >> "$OUT_FILE"
    done
    echo "" >> "$OUT_FILE"
    echo "" >> "$OUT_FILE"
    
    # Resolve dependencies
    DEP_FILES=""
    LINK_DEPS=""
    RAW_DEPS="${TARGETS_DEPS[$NAME]}"
    HAS_SHARED=0
    for dep in $RAW_DEPS; do
        D_TYPE="${TARGET_TYPE_MAP[$dep]}"
        if [[ "$D_TYPE" == "lib" ]]; then
            DEP_FILES="$DEP_FILES lib${dep}.a"
            LINK_DEPS="$LINK_DEPS lib${dep}.a"
        elif [[ "$D_TYPE" == "dll" ]]; then
            DEP_FILES="$DEP_FILES lib${dep}.so"
            LINK_DEPS="$LINK_DEPS -l${dep}"
            HAS_SHARED=1
        fi
    done
    if [[ $HAS_SHARED -eq 1 ]]; then
        LINK_DEPS="-L. $LINK_DEPS"
    fi

    # Write Target Rule
    case "$TYPE" in
        exe)
            echo "$NAME: \$(${TARGET_OBJS_VAR}) $DEP_FILES" >> "$OUT_FILE"
            echo -e "\t\$(LD) \$(LDFLAGS) \$(TGT_${SANITIZED_TARGET}_LDFLAGS) $T_FLAGS -o $NAME \$(${TARGET_OBJS_VAR}) $LINK_DEPS $T_LIBS \$(LIBS)" >> "$OUT_FILE"
            ALL_TARGETS="$ALL_TARGETS $NAME"
            ;;
        lib)
            LIBNAME="lib${NAME}.a"
            echo "$LIBNAME: \$(${TARGET_OBJS_VAR})" >> "$OUT_FILE"
            echo -e "\t\$(AR) cr $LIBNAME \$(${TARGET_OBJS_VAR})" >> "$OUT_FILE"
            ALL_TARGETS="$ALL_TARGETS $LIBNAME"
            ;;
        dll)
            # IRIX DSO usually .so
            DLLNAME="lib${NAME}.so"
            echo "$DLLNAME: \$(${TARGET_OBJS_VAR}) $DEP_FILES" >> "$OUT_FILE"
            echo -e "\t\$(LD) -shared \$(LDFLAGS) \$(TGT_${SANITIZED_TARGET}_LDFLAGS) $T_FLAGS -o $DLLNAME \$(${TARGET_OBJS_VAR}) $LINK_DEPS $T_LIBS" >> "$OUT_FILE"
            ALL_TARGETS="$ALL_TARGETS $DLLNAME"
            ;;
    esac
    echo "" >> "$OUT_FILE"
done

# Write 'all' and 'clean' variables
echo "ALL_TARGETS = $ALL_TARGETS" >> "$OUT_FILE"
echo "" >> "$OUT_FILE"

echo "Generated $OUT_FILE successfully."
